### ISSUE TITLE
Screensaver - Slideshow Custom location images folder

### ISSUE THREAD

**Issue by 2play** [RetroBat-Official/emulatorlauncher#225] opened 2023-11-06 23:08 UTC
LATEST RETROBAT 5.3:
The ES screensaver cant display any image slideshow if set to a custom location. For example if path set to emulationstation/slideshow/image no image will be displayed with slideshow setting

If though put bulk in root path /screenshots then screensaver slideshow plays ok.
Is this a bug or intended? 
Having the slideshow images in a subfolder is cleaner similar to other frontends

Kind regards

**Comment by fabricecaruso** [comment] 2023-11-06 23:40
1/ It's not the good repository to post. EmulationStation repository is there : https://github.com/batocera-linux/batocera-emulationstation
2/ I can't reproduce. You have to be more precise about every setting you set and everything that is in your folders. The informations you gave are really insuffiscient.

**Comment by 2play** [comment] 2023-11-07 00:03
> 1/ It's not the good repository to post. EmulationStation repository is there : https://github.com/batocera-linux/batocera-emulationstation 2/ I can't reproduce. You have to be more precise about every setting you set and everything that is in your folders. The informations you gave are really insuffiscient.

Apologies will do. It is little late and rushed with the info

**Comment by Tartifless** [comment] 2023-11-09 11:29
Closed as this is moved to ES github

**Closed by Tartifless** 2023-11-09 11:29 UTC
